# Configurations
title:            HE Tao
longtitle:        Hello my love
author:           HE Tao
email:            sighingnow@gmail.com
description: >
  HE Tao's homepage, for blogs, codes and other interesting things.

version:          1.0

url:              'https://rapidai.github.io/'
# url:              'http://localhost:4000'
baseurl:          ''
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

# pandoc:
#   format: html5
#   highlight-style: tango
#   extensions:
#     - smart
#     - mathjax

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        none

excerpt_separator: "<!--more-->"

# Navigation
navigation:
- text: Blog
  url: /blog/
- text: Archive
  url: /archive/
- text: Résumé
  url: /resume/
- text: Github
  url: https://github.com/sighingnow
  external: true

exclude:
  - _drafts

#Social Media links
social:
  github:         sighingnow
  facebook:       sighingnow
  linkedin:       涛-何-732868bb
  pinterest:      sighingnow
  twitter:        sighingnow
  stackoverflow:  users/5080177/he-tao

# Google Analytics
gahandler:        'UA-124803592-1'

# CNZZ
cnzzhandler:      '1277366039'

# Disqus
disqushandler:    'sighingnow'

# Blog Configurations
paginate:         10 # Posts per page on the blog index
paginate_path:    '/blog/page:num'
destination:      ./_site
incremental:      true
regenerate:       false

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
